<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(ProjectTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="$(CommunityToolkitMvvmVersion)" />
    <PackageReference Include="AgredoApplication.MVVM.Services" Version="$(AgredoMvvmServicesVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniTracks.Services\UniTracks.Services.csproj" />
    <ProjectReference Include="..\UniTracks.Data\UniTracks.Data.csproj" />
    <ProjectReference Include="..\UniTracks.Models\UniTracks.Models.csproj" />
  </ItemGroup>

</Project>
