// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniTracks.Data.SQLite;

#nullable disable

namespace UniTracks.Data.Migrations
{
    [DbContext(typeof(SqliteDBContext))]
    [Migration("20240521220010_AddedTripTypeSeeds")]
    partial class AddedTripTypeSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("UniTracks.Models.Environment.Weather", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CloudCover")
                        .HasColumnType("REAL");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("TEXT");

                    b.Property<double>("Pressure")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TripID")
                        .HasColumnType("TEXT");

                    b.Property<double>("WindDirection")
                        .HasColumnType("REAL");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("TripID");

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("UniTracks.Models.Health.HeartRate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TripID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TripID");

                    b.ToTable("HeartRates");
                });

            modelBuilder.Entity("UniTracks.Models.Health.Weight", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TripID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightValue")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("TripID");

                    b.HasIndex("UserID");

                    b.ToTable("Weights");
                });

            modelBuilder.Entity("UniTracks.Models.Location.Location", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<double>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Heading")
                        .HasColumnType("REAL");

                    b.Property<double>("HeadingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Speed")
                        .HasColumnType("REAL");

                    b.Property<double>("SpeedAccuracy")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TripID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TripID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("UniTracks.Models.Trip.Trip", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxAltitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxHeading")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxHeadingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxSpeedAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinAltitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinHeading")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinHeadingAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinSpeed")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinSpeedAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double?>("MovingTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StoppedTime")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalTime")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("UniTracks.Models.Trip.TripType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TripTypes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000001"),
                            Category = "running",
                            Description = "",
                            Identifier = "run",
                            Name = "Run"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000002"),
                            Category = "running",
                            Description = "",
                            Identifier = "trailrun",
                            Name = "Trail Run"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000003"),
                            Category = "running",
                            Description = "",
                            Identifier = "walk",
                            Name = "Walk"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000004"),
                            Category = "running",
                            Description = "",
                            Identifier = "hiking",
                            Name = "Hiking"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000005"),
                            Category = "cycling",
                            Description = "",
                            Identifier = "cycling",
                            Name = "Cycling"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000006"),
                            Category = "cycling",
                            Description = "",
                            Identifier = "mountainbiking",
                            Name = "Mountain Biking"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000007"),
                            Category = "cycling",
                            Description = "",
                            Identifier = "gravelride",
                            Name = "Gravel Ride"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000008"),
                            Category = "cycling",
                            Description = "",
                            Identifier = "ebikeride",
                            Name = "E-Bike Ride"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000009"),
                            Category = "cycling",
                            Description = "",
                            Identifier = "emountainbikeride",
                            Name = "E-Mountainbike Ride"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000010"),
                            Category = "cycling",
                            Description = "",
                            Identifier = "velobikeride",
                            Name = "Velobike Ride"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000011"),
                            Category = "winter sports",
                            Description = "",
                            Identifier = "skiing",
                            Name = "Skiing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000012"),
                            Category = "winter sports",
                            Description = "",
                            Identifier = "snowboarding",
                            Name = "Snowboarding"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000013"),
                            Category = "winter sports",
                            Description = "",
                            Identifier = "crosscountryskiing",
                            Name = "Cross Country Skiing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000014"),
                            Category = "winter sports",
                            Description = "",
                            Identifier = "backcountryskiing",
                            Name = "Backcountry Skiing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000015"),
                            Category = "winter sports",
                            Description = "",
                            Identifier = "telemarkskiing",
                            Name = "Telemark Skiing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000016"),
                            Category = "winter sports",
                            Description = "",
                            Identifier = "snowshoeing",
                            Name = "Snowshoeing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000017"),
                            Category = "winter sports",
                            Description = "",
                            Identifier = "alpineskiing",
                            Name = "Alpine Skiing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000018"),
                            Category = "winter sports",
                            Description = "",
                            Identifier = "snowshoehike",
                            Name = "Snowshoe Hike"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000019"),
                            Category = "skating",
                            Description = "",
                            Identifier = "skating",
                            Name = "Skating"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000020"),
                            Category = "skating",
                            Description = "",
                            Identifier = "inlineskating",
                            Name = "Inline Skating"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000021"),
                            Category = "skating",
                            Description = "",
                            Identifier = "rollerskating",
                            Name = "Roller Skating"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000022"),
                            Category = "skating",
                            Description = "",
                            Identifier = "iceskating",
                            Name = "Ice Skating"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000023"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "swimming",
                            Name = "Swimming"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000024"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "openwaterswimming",
                            Name = "Open Water Swimming"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000025"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "poolswimming",
                            Name = "Pool Swimming"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000026"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "lapswimming",
                            Name = "Lap Swimming"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000027"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "kanu",
                            Name = "Kanu"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000028"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "kayak",
                            Name = "Kayak"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000029"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "standuppaddling",
                            Name = "Stand Up Paddling"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000030"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "rowing",
                            Name = "Rowing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000031"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "dragonboat",
                            Name = "Dragon Boat"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000032"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "sailing",
                            Name = "Sailing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000033"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "surfing",
                            Name = "Surfing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000034"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "kitesurfing",
                            Name = "Kitesurfing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000035"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "windsurfing",
                            Name = "Windsurfing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000036"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "wakeboarding",
                            Name = "Wakeboarding"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000037"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "wakesurfing",
                            Name = "Wakesurfing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000038"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "waterskiing",
                            Name = "Water Skiing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000039"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "jetskiing",
                            Name = "Jet Skiing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000040"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "diving",
                            Name = "Diving"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000041"),
                            Category = "water sports",
                            Description = "",
                            Identifier = "freediving",
                            Name = "Freediving"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000042"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "golf",
                            Name = "Golf"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000043"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "horsebackriding",
                            Name = "Horseback Riding"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000044"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "climbing",
                            Name = "Climbing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000045"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "bouldering",
                            Name = "Bouldering"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000046"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "indoorclimbing",
                            Name = "Indoor Climbing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000047"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "outdoorclimbing",
                            Name = "Outdoor Climbing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000048"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "iceclimbing",
                            Name = "Ice Climbing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000049"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "mountaineering",
                            Name = "Mountaineering"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000050"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "viaferrata",
                            Name = "Via Ferrata"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000051"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "canyoning",
                            Name = "Canyoning"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000052"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "skateboarding",
                            Name = "Skateboarding"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000053"),
                            Category = "miscellaneous",
                            Description = "",
                            Identifier = "longboarding",
                            Name = "Longboarding"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000054"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "fitness",
                            Name = "Fitness"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000055"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "crossfit",
                            Name = "Crossfit"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000056"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "yoga",
                            Name = "Yoga"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000057"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "pilates",
                            Name = "Pilates"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000058"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "barre",
                            Name = "Barre"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000059"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "zumba",
                            Name = "Zumba"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000060"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "dance",
                            Name = "Dance"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000061"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "aerobics",
                            Name = "Aerobics"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000062"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "stepaerobics",
                            Name = "Step Aerobics"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000063"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "spinning",
                            Name = "Spinning"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000064"),
                            Category = "fitness",
                            Description = "",
                            Identifier = "indoorcycling",
                            Name = "Indoor Cycling"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000065"),
                            Category = "fighting sports",
                            Description = "",
                            Identifier = "boxing",
                            Name = "Boxing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000066"),
                            Category = "fighting sports",
                            Description = "",
                            Identifier = "kickboxing",
                            Name = "Kickboxing"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000067"),
                            Category = "fighting sports",
                            Description = "",
                            Identifier = "martialarts",
                            Name = "Martial Arts"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000068"),
                            Category = "fighting sports",
                            Description = "",
                            Identifier = "taekwondo",
                            Name = "Taekwondo"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000069"),
                            Category = "fighting sports",
                            Description = "",
                            Identifier = "karate",
                            Name = "Karate"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000070"),
                            Category = "fighting sports",
                            Description = "",
                            Identifier = "judo",
                            Name = "Judo"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000071"),
                            Category = "fighting sports",
                            Description = "",
                            Identifier = "jiujitsu",
                            Name = "Jiu Jitsu"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000072"),
                            Category = "fighting sports",
                            Description = "",
                            Identifier = "wrestling",
                            Name = "Wrestling"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000073"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "football",
                            Name = "Football"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000074"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "soccer",
                            Name = "Soccer"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000075"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "volleyball",
                            Name = "Volleyball"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000076"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "beachvolleyball",
                            Name = "Beach Volleyball"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000077"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "tennis",
                            Name = "Tennis"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000078"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "tabletennis",
                            Name = "Table Tennis"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000079"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "badminton",
                            Name = "Badminton"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000080"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "squash",
                            Name = "Squash"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000081"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "racquetball",
                            Name = "Racquetball"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000082"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "handball",
                            Name = "Handball"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000083"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "basketball",
                            Name = "Basketball"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000084"),
                            Category = "ball sports",
                            Description = "",
                            Identifier = "americanfootball",
                            Name = "American Football"
                        });
                });

            modelBuilder.Entity("UniTracks.Models.User.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("MedicalConditions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medications")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniTracks.Models.Environment.Weather", b =>
                {
                    b.HasOne("UniTracks.Models.Location.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniTracks.Models.Trip.Trip", null)
                        .WithMany("Weather")
                        .HasForeignKey("TripID");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("UniTracks.Models.Health.HeartRate", b =>
                {
                    b.HasOne("UniTracks.Models.Trip.Trip", null)
                        .WithMany("HeartRates")
                        .HasForeignKey("TripID");
                });

            modelBuilder.Entity("UniTracks.Models.Health.Weight", b =>
                {
                    b.HasOne("UniTracks.Models.Trip.Trip", null)
                        .WithMany("Weights")
                        .HasForeignKey("TripID");

                    b.HasOne("UniTracks.Models.User.User", null)
                        .WithMany("Weights")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("UniTracks.Models.Location.Location", b =>
                {
                    b.HasOne("UniTracks.Models.Trip.Trip", null)
                        .WithMany("Locations")
                        .HasForeignKey("TripID");
                });

            modelBuilder.Entity("UniTracks.Models.Trip.Trip", b =>
                {
                    b.HasOne("UniTracks.Models.User.User", null)
                        .WithMany("Trips")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("UniTracks.Models.Trip.Trip", b =>
                {
                    b.Navigation("HeartRates");

                    b.Navigation("Locations");

                    b.Navigation("Weather");

                    b.Navigation("Weights");
                });

            modelBuilder.Entity("UniTracks.Models.User.User", b =>
                {
                    b.Navigation("Trips");

                    b.Navigation("Weights");
                });
#pragma warning restore 612, 618
        }
    }
}
