<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(ProjectTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AgredoApplication.MVVM.Services" Version="$(AgredoMvvmServicesVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniTracks.Data\UniTracks.Data.csproj" />
  </ItemGroup>

</Project>
